dist: bionic
language: python
python:
- 3.6
env:
  global:
  - VAGRANT_VER: 2.2.9
  matrix:
  - MOLECULE_DISTRO_BOX: enr0s/ubuntu-focal
install:
- sudo add-apt-repository universe && sudo apt update
- wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
- sudo dpkg -i vagrant_"$VAGRANT_VER"_x86_64.deb
- sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev sshpass
- vagrant plugin install vagrant-libvirt
- pip install molecule=='3.0.6' molecule-vagrant docker python-vagrant paramiko ansible-lint
  yamllint travis-wait-improved
- sudo chmod o+rwx /var/run/libvirt/libvirt-sock
script:
- ansible --version
- molecule --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
- travis-wait-improved --timeout 30m molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: grGSUjLWVKL1jR8dswOPHt72DbpmxvuQIQT5TR359yK5aRDja+8Zh5lUD7stCAwiiC7zTrWyklDRzXBo2sT7L2Hcz1ErW0awpQajm6NO9rNqzbP/yFZJndCG+2xaqksnVlRscEvhyIaq5Pdceau1ZY8CrtBHWSAP3xUWIqwbtmgquQnTZ0IQ48V4qh+s/mMGRQ/SZnx54lom9nVHoXCvDGr4JR72A4v/wzQMlZKMshW71XALQNGxyQpH0ayQxEaS233sdsjzjz9CA/NIEQuqUDd/inllKdpgyBCvVoSwwDB/9X8V1lHzMSlxdMMbX41RwVdXGA9LLqBHqcp625xRZfO3YCCusGG9yOiJ/s9z1ypNtClTvBsIlXc5Z4aTHIsc4a9Au80kUTg3DY1kNhs87IzgsAZxg2LYBedCuGz0p7xMoKB9Ug5GRJUCaDEt3dupz/EXmgcZYLfSoGyOwT//In9f1SmYROrK4/IUXnnSl9iX/tpUG7IsK16PYKbPgNTBNahy+o4DeMHcOI61NXyVEa03qA3MniYKBEzmc7sZx8aoPvbmCTFRW7n3UTquS1cYnNZ8lKZzYB5sUOly4WuI5h2j/WebZOdxztaymjp7i3PD+zMTTQC3iH0blrAn0RaZiAmqQaJ5HEwyeVo891VWxhOLz6heMeHj1IWNPdU9ewk=
