dist: bionic
language: python
python:
- 3.6
env:
  global:
  - VAGRANT_VER: 2.2.9
  matrix:
  - MOLECULE_DISTRO_BOX: enr0s/ubuntu-focal
install:
- sudo add-apt-repository universe && sudo apt update
- wget https://releases.hashicorp.com/vagrant/$VAGRANT_VER/vagrant_"$VAGRANT_VER"_x86_64.deb
- sudo dpkg -i vagrant_"$VAGRANT_VER"_x86_64.deb
- sudo apt install qemu-kvm qemu-utils libvirt-bin libvirt0 libvirt-dev sshpass
- vagrant plugin install vagrant-libvirt
- pip install molecule=='3.0.6' molecule-vagrant docker python-vagrant paramiko ansible-lint yamllint travis-wait-improved
- sudo chmod o+rwx /var/run/libvirt/libvirt-sock
script:
- ansible --version
- molecule --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
- travis-wait-improved --timeout 30m molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: IboUgI8+kARmwx6YHMI6zoeXGmccpsWAUgII3oMsugLWOw6K+xdASGCb54GWZr4Nr6UONeBmw5BwnkzUNkyUfP8MdEt5HXPrYfl6Hwu7qXdo0qy2o+Uq2m66kupB+16vhUIVmva7JBi3QlM0zPEMxnHtGrqwHq9EepIL+iFQ7UYIplyn7Z/creKLPQpCzYshoBqVzhg8UHX/RvrCBBgZQru9wXay/R+YVbpMUAwoLWihWP3QmSw9FMV3NFbXaYEbDxn2qhpKhbUhtY+ujPPvcStvTU9TLXg5QrrvzdADs1rnJDjuqCGPoUoaguJuCP81ePsUDwoZ5dEwsG2HdbhF/CI7IQpvCpambFjaq/ZG1DyhIdbSH+WzRFB0ywecTFBVxCG2LFBt6sKqy4RETODHEDPTWlgC7lfOprWGHVsB3sqYvugpxj8mwJlHvUvnXBqJlxcOqys3Pn65zaq1lsT8mIXuRrZTDmh82Zx8wmc9gLAAVXSKVb1sEM5NgwlJU5w+kR+dPS+uhJfKtve2K/+MofLjjRapXaiwTOEUlt41pp9nxsvGn9pbsUHjnzd0D1XQL3fun4bsp8g8dfNd09dTnPm7R940Jm2IKe2MrxHLkbvZU4s5l4j7RbQi9vFYQCk0M+TYrhPyZAvXWxnqSsGLS5p5upP0a9yzmb/LqsdgLtQ=
