---
dependency:
  name: galaxy
lint: |
  yamllint .
  ansible-lint
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: bootstrap
    box: ${MOLECULE_DISTRO_BOX:-""}
    memory: 1024
    cpus: 2
    provision: yes
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  options:
    vvv: false
  inventory:
    group_vars:
      all:
        ansible_ssh_user: vagrant
        ansible_ssh_pass: vagrant
verifier:
  name: ansible
